# Site settings
title: Habedi.me
email: hassan.abedi.t@gmail.com
description: >
  Our website.

baseurl: "/" # the subpath of your site, e.g. /blog/
url: http://habedi.me # the base hostname & protocol for your site
git_address: https://github.com/Cirice/cirice.github.io
git_edit_address: https://github.com/Cirice/cirice.github.io/blob/gh-pages

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: cerulean

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: Asia/Tehran
defaults:

- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog
    
- scope:
    path: _datascience
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
