#!/usr/bin/env bash

# set -e # halt script on error

bundle install # install missing gems
bundle exec jekyll build
bundle exec htmlproofer ./_site
exit 0 # not sure htmlproofer is usable for my site or not!
